USE YarnStore;
GO

CREATE TABLE Brand (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Country NVARCHAR(100) NOT NULL
);

CREATE TABLE Category (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	TypeName NVARCHAR(100) NOT NULL
);

CREATE TABLE Yarn (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	Name NVARCHAR(100) NOT NULL,
	PricePer100g DECIMAL(10,2) NOT NULL,
	StockQuantity INT NOT NULL,
	IsInStock BIT NOT NULL,
	CreatedAt DATE NOT NULL DEFAULT GETDATE(),
	BrandId INT NOT NULL,
	CategoryId INT NOT NULL,
	FOREIGN KEY (BrandId) REFERENCES Brand(Id),
	FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);

CREATE TABLE Customer (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FullName NVARCHAR(200) NOT NULL,
	Email NVARCHAR(200) NOT NULL,
	RegisteredAt DATETIME NOT NULL DEFAULT GETDATE(),
);

CREATE UNIQUE INDEX IX_Customer_Email ON Customer(Email);

CREATE TABLE [Order] (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	CustomerId UNIQUEIDENTIFIER NOT NULL,
	OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
	TotalCost DECIMAL(12,2) NOT NULL
	FOREIGN KEY (CustomerId) REFERENCES Customer(Id)
);

CREATE TABLE OrderItem (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	OrderId UNIQUEIDENTIFIER NOT NULL,
	YarnId UNIQUEIDENTIFIER NOT NULL,
	Quantity INT NOT NULL,
	PriceAtPurchase DECIMAL(10,2),
	FOREIGN KEY (OrderId) REFERENCES [Order](Id),
	FOREIGN KEY (YarnId) REFERENCES Yarn(Id)
);