-- Удаление записей с ценником менее 250 рублей из таблицы Yarn.

SELECT * FROM Yarn WHERE PricePer100g < 250.00;

BEGIN TRANSACTION;

ALTER TABLE [OrderItem] NOCHECK CONSTRAINT [FK__OrderItem__YarnI__5EBF139D];

DELETE FROM Yarn WHERE PricePer100g < 250.00;

SELECT * FROM Yarn WHERE PricePer100g < 250.00;

ROLLBACK TRANSACTION;

ALTER TABLE [OrderItem] WITH CHECK CHECK CONSTRAINT ALL;

SELECT * FROM Yarn WHERE PricePer100g < 250.00;